apiVersion: v1
kind: Pod
metadata:
  name: unauthorized-test
  namespace: payments
  labels:
    app: unauthorized-test
spec:
  serviceAccountName: default
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: unauthorized-test
      image: curlimages/curl:latest
      command: ["sleep", "3600"]
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
